# Generated by Django 6.0.2 on 2026-03-13 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_delete_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abierta', models.BooleanField(default=True)),
                ('mensaje_cierre', models.CharField(default='La tienda está cerrada en este momento. ¡Vuelve pronto!', max_length=255)),
            ],
            options={
                'verbose_name': 'Configuración de tienda',
                'verbose_name_plural': 'Configuración de tienda',
            },
        ),
    ]
