# Generated by Django 5.2.7 on 2026-04-14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ConfigTienda",
            new_name="StoreConfig",
        ),
        migrations.RenameField(
            model_name="storeconfig",
            old_name="abierta",
            new_name="is_open",
        ),
        migrations.RenameField(
            model_name="storeconfig",
            old_name="mensaje_cierre",
            new_name="closed_message",
        ),
    ]
