# Generated by Django 6.0.2 on 2026-04-16 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_configtienda_storeconfig_and_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storeconfig',
            options={'verbose_name': 'Store Configuration', 'verbose_name_plural': 'Store Configuration'},
        ),
        migrations.AlterField(
            model_name='storeconfig',
            name='closed_message',
            field=models.CharField(default='The store is currently closed. Come back soon!', max_length=255),
        ),
    ]
