# Generated by Django 5.2.7 on 2026-04-15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carrito", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Pedido",
            new_name="Order",
        ),
        migrations.RenameModel(
            old_name="ItemPedido",
            new_name="OrderItem",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="usuario",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="fecha",
            new_name="date",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="estado",
            new_name="status",
        ),
        migrations.RenameField(
            model_name="orderitem",
            old_name="pedido",
            new_name="order",
        ),
        migrations.RenameField(
            model_name="orderitem",
            old_name="producto_id",
            new_name="product_id",
        ),
        migrations.RenameField(
            model_name="orderitem",
            old_name="nombre",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="orderitem",
            old_name="precio",
            new_name="price",
        ),
        migrations.RenameField(
            model_name="orderitem",
            old_name="cantidad",
            new_name="quantity",
        ),
    ]
