# Generated by Django 5.2.7 on 2026-04-15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carrito", "0003_rename_imagen_orderitem_image"),
    ]

    operations = [
        migrations.RunSQL(
            sql=migrations.RunSQL.noop,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
