# Generated by Django 5.2.7 on 2026-04-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0002_remove_producto_creado_remove_producto_disponible_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Producto",
            new_name="Product",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="nombre",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="precio",
            new_name="price",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="imagen",
            new_name="image",
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
    ]
