# Generated by Django 5.2.7 on 2026-04-15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_rename_pedido_order_and_fields"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="imagen",
            new_name="image",
        ),
    ]
