# Generated by Django 6.0.1 on 2026-05-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_rename_producto_product_and_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción del producto visible al hacer clic en la tarjeta.', null=True, verbose_name='Descripción'),
        ),
    ]
